services:
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: pkmn-timescale
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pkmn
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d pkmn"]
      interval: 5s
      timeout: 3s
      retries: 20
volumes:
  db_data:
