# .github/workflows/nightly.yml
name: Nightly Backtests

on:
  schedule:
    - cron: "0 7 * * *"   # 07:00 UTC nightly
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest

    services:
      timescaledb:
        image: timescale/timescaledb-ha:pg16-latest
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: pkmn
        options: >-
          --health-cmd="pg_isready -U postgres -d pkmn"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python & uv
        uses: astral-sh/setup-uv@v3
        with:
          python-version: "3.12"

      - name: Install (editable)
        run: |
          uv pip install -e .

      - name: Apply migrations
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/pkmn
        run: |
          PYTHONPATH=src uv run alembic upgrade head

      - name: Run nightly backtests
        env:
          DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/pkmn
        run: |
          uv run python -m pkmn_factors.ops.run_nightly \
            --universe data/universe_demo.csv \
            --model-version bhs_baseline_v2 \
            --horizon-days 90 \
            --persist \
            --refresh-cagg \
            --max-concurrency 5 \
            --note "github nightly"
