name: run-nightly

on:
  schedule:
    - cron: '20 6 * * *' # daily at 06:20 UTC
  workflow_dispatch:

concurrency:
  group: run-nightly
  cancel-in-progress: false

jobs:
  run-nightly:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: timescale/timescaledb:2.13.1-pg15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pkmn
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 20

    env:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/pkmn
      PGPASSWORD: postgres

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        run: pipx install uv

      - name: Create virtualenv (uv) and expose it
        run: |
          uv venv
          echo "$GITHUB_WORKSPACE/.venv/bin" >> $GITHUB_PATH
          echo "VIRTUAL_ENV=$GITHUB_WORKSPACE/.venv" >> $GITHUB_ENV

      - name: Wait for DB & create Timescale extension
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 2
          done
          psql -h localhost -p 5432 -U postgres -d pkmn -c "CREATE EXTENSION IF NOT EXISTS timescaledb;"

      - name: Install deps (runtime + dev)
        run: uv pip install -e ".[dev]"

      - name: Lint/Type/Test (sanity)
        run: |
          uv run ruff check .
          uv run mypy src
          uv run pytest -q

      - name: Run migrations
        run: uv run alembic upgrade head

      - name: Run nightly
        run: |
          uv run python -m pkmn_factors.ops.run_nightly \
            --universe data/universe_demo.csv \
            --model-version bhs_baseline_v2 \
            --horizon-days 90 \
            --persist \
            --refresh-cagg \
            --max-concurrency 5
