name: nightly

on:
  workflow_dispatch:
  schedule:
    # 07:15 UTC every day — adjust to taste
    - cron: "15 7 * * *"
  push:
    branches:
      - feat/nightly-runner-v2

jobs:
  run-nightly:
    runs-on: ubuntu-latest

    services:
      db:
        image: timescale/timescaledb:2.16.1-pg16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: pkmn
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres -d pkmn"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=15

    env:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@localhost:5432/pkmn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv
        run: pipx install uv

      - name: Install deps (runtime + dev)
        run: uv pip install -e ".[dev]"

      - name: Lint/Type/Test (sanity)
        run: |
          uv run ruff check .
          uv run black --check .
          uv run mypy src
          uv run pytest -q

      - name: Run migrations
        run: uv run alembic upgrade head

      - name: Run nightly
        run: |
          uv run python -m pkmn_factors.ops.run_nightly \
            --universe data/universe_demo.csv \
            --model-version bhs_baseline_v2 \
            --horizon-days 90 \
            --persist \
            --refresh-cagg \
            --max-concurrency 4
